Traceback (most recent call last):
  File "/home/hjj/01_VPI/main.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
2025-06-21 16:08:19,347 [INFO] file_cache is only supported with oauth2client<4.0.0
2025-06-21 16:15:59,786 [INFO] file_cache is only supported with oauth2client<4.0.0
