[✅] 사용 중인 API KEY: AIzaSyBKMDyoWL7TeEXOpwjaJLSGtM5NYYKoNcQ
[✅] 사용 중인 API KEY: AIzaSyBKMDyoWL7TeEXOpwjaJLSGtM5NYYKoNcQ
[✅] 사용 중인 API KEY: AIzaSyBKMDyoWL7TeEXOpwjaJLSGtM5NYYKoNcQ
[✅] 사용 중인 API KEY: AIzaSyBKMDyoWL7TeEXOpwjaJLSGtM5NYYKoNcQ
Traceback (most recent call last):
  File "/home/hjj/01_VPI_data/main.py", line 12, in <module>
    logging.basicConfig(
  File "/usr/lib/python3.10/logging/__init__.py", line 2040, in basicConfig
    h = FileHandler(filename, mode,
  File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
FileNotFoundError: [Errno 2] No such file or directory: '/home/hjj/logs/log.txt'
[✅] 사용 중인 API KEY: AIzaSyBKMDyoWL7TeEXOpwjaJLSGtM5NYYKoNcQ
[✅] 사용 중인 API KEY: AIzaSyBKMDyoWL7TeEXOpwjaJLSGtM5NYYKoNcQ
[✅] 사용 중인 API KEY: AIzaSyBKMDyoWL7TeEXOpwjaJLSGtM5NYYKoNcQ
[✅] 사용 중인 API KEY: AIzaSyBKMDyoWL7TeEXOpwjaJLSGtM5NYYKoNcQ
Traceback (most recent call last):
  File "/home/hjj/01_VPI_data/main.py", line 12, in <module>
    logging.basicConfig(
  File "/usr/lib/python3.10/logging/__init__.py", line 2040, in basicConfig
    h = FileHandler(filename, mode,
  File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
FileNotFoundError: [Errno 2] No such file or directory: '/home/hjj/logs/log.txt'
[✅] 사용 중인 API KEY: AIzaSyBKMDyoWL7TeEXOpwjaJLSGtM5NYYKoNcQ
[✅] 사용 중인 API KEY: AIzaSyBKMDyoWL7TeEXOpwjaJLSGtM5NYYKoNcQ
[✅] 사용 중인 API KEY: AIzaSyBKMDyoWL7TeEXOpwjaJLSGtM5NYYKoNcQ
[✅] 사용 중인 API KEY: AIzaSyBKMDyoWL7TeEXOpwjaJLSGtM5NYYKoNcQ
Traceback (most recent call last):
  File "/home/hjj/01_VPI_data/main.py", line 12, in <module>
    logging.basicConfig(
  File "/usr/lib/python3.10/logging/__init__.py", line 2040, in basicConfig
    h = FileHandler(filename, mode,
  File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
FileNotFoundError: [Errno 2] No such file or directory: '/home/hjj/logs/log.txt'
